more changes

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -8,14 +8,18 @@ env:
   global:
   - VERSION="0.11.0"
 
-before_script:
+before_check:
   - curl -fSL "https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip" -o terraform.zip
   - sudo unzip terraform.zip -d /opt/terraform
   - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
   - rm -f terraform.zip
   - terraform version
-script:
-  - ./test/check-fmt.sh
+check:
+  - terraform fmt -check=true -diff=true
+    if [ $? -ne 3 ]; then
+      echo "ERROR:failed to pass terraform fmt"
+      exit 1
+    fi 
 
 notifications:
   email: false
